### ISSUE TITLE
Error when trying to update to new repos

### ISSUE THREAD

**Issue by trentraber** [BSData/wh40k-9e#11496]
**Describe the bug**
The MacOS desktop app is failing to download the new release with the Nephalim data.

**To Reproduce**
1. Click on Manage Data
2. Click on Update Data
3. Receive Error

**Expected behavior**
The update should be retrievable with no errors

**Screenshots**
No Screenshots, but here is the error output
Details:

Failed to download from one or more repositories

1) net.battlescribe.model.config.Repository@ad66e59: https://battlescribedata.appspot.com/repos/wh40k

2) https://battlescribedata.appspot.com/repos/wh40k/index.bsi: https://battlescribedata.appspot.com/repos/wh40k/index.bsi
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.a(BattleScribe:525)
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.call(BattleScribe:481)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Device and data (please complete the following information):**
 - OS: MacOS
 - BattleScribe version 2.03.21
 - Release version 9.4.1

**Additional context**
This seems to be happening in both the MacOS Desktop application and the iOS application.  I deleted my Mac application and tried to reinstall, and I removed all the data also, but now I do not have access to the WH 9th edition data source.  I can't even add WH to the app now.

**Comment by AbonShell** [comment]
not a problem with this repo, its a problem with appspot, nothing we can do

**Comment by AbonShell** [comment]
https://github.com/BSData/wh40k/issues/1706
