### ISSUE TITLE
Repo Server Down

### ISSUE THREAD

**Issue by cyberpika2** [BSData/wh40k-9e#8049]
**File/Catalogue:** 
Warhammer 40,000 v9.0.12 & Warhammer 40,000: 7th edition v7.0.1
**BattleScribe version:** 2.03.
2.03.21.166
**Platform:** Windows/iOS/Android/Mac/Linux
PC / iOS / Windows passes for all
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.

Repo server down.
Status 404.
Cannot report on appspot 
Status 404
http://battlescribedata.appspot.com/#/repo/wh40k
https://battlescribedata.appspot.com/repos/wh40k/index.bsi
Resolving to 172.253.124.153 / 2607:f8b0:4002:c10::99

-----------------

BS Windows OUTPUT:
```
1) net.battlescribe.model.config.Repository@1d1876f: https://battlescribedata.appspot.com/repos/wh40k

2) https://battlescribedata.appspot.com/repos/wh40k/index.bsi: https://battlescribedata.appspot.com/repos/wh40k/index.bsi

3) net.battlescribe.model.config.Repository@1042cfb: https://battlescribedata.appspot.com/repos/wh40k-7th-edition

4) https://battlescribedata.appspot.com/repos/wh40k-7th-edition/index.bsi: https://battlescribedata.appspot.com/repos/wh40k-7th-edition/index.bsi
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.a(BattleScribe:525)
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.call(BattleScribe:481)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```
Thank you!

**Comment by Mad-Spy** [comment]
We know. It happens all the time, as per the pinned issue on the front page - #1706
