### ISSUE TITLE
error when trying to updated data

### ISSUE THREAD

**Issue by ThomasRae** [BSData/wh40k-9e#8057]
**File/Catalogue:** 
Warhammer 40k v9.0.13
Warhammer 40k Apocaplypse v1.1.6

**BattleScribe version:** 2.03.21.166

**Platform:** Windows/
**Dropbox:** No

**Description:**
WHen trying to update data im getting this back
Details:

Failed to download from one or more repositories

1) net.battlescribe.model.config.Repository@120e5cb: https://battlescribedata.appspot.com/repos/wh40k

2) https://battlescribedata.appspot.com/repos/wh40k/index.bsi: https://battlescribedata.appspot.com/repos/wh40k/index.bsi

3) net.battlescribe.model.config.Repository@bf29c9: https://battlescribedata.appspot.com/repos/wh40k-apocalypse

4) https://battlescribedata.appspot.com/repos/wh40k-apocalypse/index.bsi: https://battlescribedata.appspot.com/repos/wh40k-apocalypse/index.bsi
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.a(BattleScribe:525)
	at net.battlescribe.desktop.common.BattleScribeWindowController$e.call(BattleScribe:481)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by williamcaw** [comment]
ITS a KNOWN ISSUE and is PINED #1706

**Comment by Technoblazed** [comment]
Reference https://github.com/BSData/wh40k/issues/1706.
