### ISSUE TITLE
net.battlescribe.a.c.g: A data file or roster is too old and can no longer be opened by this version of BattleScribe.

### ISSUE THREAD

**Issue by killer00z** [BSData/wh40k-9e#8678]
Cant import manuały data (i tryed:Necrons.cat and Imperium - Ultramarines.cat)
There is no 8, 9 edition on a Battlescribe data list

**BattleScribe version:** 2.03.21.166

**Platform:** Windows10

**Dropbox:** No

**Description:** 
Details:

net.battlescribe.a.c.g: A data file or roster is too old and can no longer be opened by this version of BattleScribe.

	at net.battlescribe.a.c.e.b(BattleScribe:681)
	at net.battlescribe.a.c.e.b(BattleScribe:570)
	at net.battlescribe.a.a.b(BattleScribe:1528)
	at net.battlescribe.a.a.a(BattleScribe:1488)
	at net.battlescribe.desktop.common.ManageDataWindowController$c.a(BattleScribe:296)
	at net.battlescribe.desktop.common.ManageDataWindowController$c.call(BattleScribe:294)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by acebaur** [comment]
Well you can't just import one cat of SM. You need the librsry and the GST as well. It is highly recommended that you download the entire file and delete and replace the the existing data if you want to side load. If you are trying to open and old roster it is probably not possible if it's old enough.

**Comment by killer00z** [comment]
thanks! i downloaded all files and imported them manualy and now i can make my roster :).
